# Generated by Django 5.0.6 on 2024-09-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MOD', 'Moderator'), ('EXP', 'Expert')], default='EXP', max_length=3),
        ),
    ]
