# Generated by Django 5.1.1 on 2024-09-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('MOD', 'Moderator'), ('EXP', 'Expert')], default='EXP', max_length=3, verbose_name='role'),
        ),
    ]
