# Generated by Django 5.0.6 on 2024-10-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='checks_available',
            field=models.PositiveIntegerField(default=1, help_text='Number of documents user can check.', verbose_name='checks available'),
        ),
    ]
