# Generated by Django 5.0.6 on 2025-01-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_address_customuser_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='iin',
            field=models.IntegerField(blank=True, null=True, verbose_name='IIN'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='middle name'),
        ),
    ]
