# Generated by Django 5.0.6 on 2025-02-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_iin_customuser_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='iin',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='IIN'),
        ),
    ]
