# Generated by Django 5.0.6 on 2024-09-07 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the organization', max_length=200)),
                ('city', models.CharField(choices=[('ALA', 'Almaty'), ('NQZ', 'Astana'), ('KGF', 'Karaganda'), ('CIT', 'Shymkent'), ('AKX', 'Aktobe'), ('PWQ', 'Pavlodar'), ('UKK', 'Oskemen')], help_text='City where the organization is based', max_length=3)),
                ('address', models.CharField(help_text='Full address of the organization', max_length=300)),
                ('description', models.TextField(blank=True, help_text='Short information about the organization')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
