# Generated by Django 5.0.6 on 2024-09-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='owner',
            new_name='created_by',
        ),
    ]
