# Generated by Django 5.0.6 on 2024-10-04 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_organization_created_at_organization_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='checks_available',
            field=models.PositiveIntegerField(default=10, help_text='Number of documents the organization can check.', verbose_name='checks available'),
        ),
    ]
