# Generated by Django 5.0.6 on 2024-11-04 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_organization_checks_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(choices=[('ALA', 'Almaty'), ('NQZ', 'Astana'), ('KGF', 'Karaganda'), ('KZO', 'Kyzylorda'), ('CIT', 'Shymkent'), ('AKX', 'Aktobe'), ('PWQ', 'Pavlodar'), ('UKK', 'Oskemen')], help_text='City where the organization is based', max_length=3),
        ),
    ]
