# Generated by Django 5.0.6 on 2024-11-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='address',
            field=models.CharField(help_text='Full address of the organization', max_length=300, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(choices=[('ALA', 'Almaty'), ('NQZ', 'Astana'), ('KGF', 'Karaganda'), ('KZO', 'Kyzylorda'), ('CIT', 'Shymkent'), ('AKX', 'Aktobe'), ('PWQ', 'Pavlodar'), ('UKK', 'Oskemen')], help_text='City where the organization is based', max_length=3, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=models.TextField(blank=True, help_text='Short information about the organization', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='title',
            field=models.CharField(help_text='Name of the organization', max_length=200, verbose_name='Title'),
        ),
    ]
