# Generated by Django 5.0.6 on 2024-11-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0007_alter_organization_address_alter_organization_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(choices=[('ALA', 'Almaty'), ('NQZ', 'Astana'), ('KGF', 'Karaganda'), ('KOV', 'Kokshetau'), ('KZO', 'Kyzylorda'), ('CIT', 'Shymkent'), ('AKX', 'Aktobe'), ('PWQ', 'Pavlodar'), ('UKK', 'Oskemen')], help_text='City where the organization is based', max_length=3, verbose_name='City'),
        ),
    ]
