# Generated by Django 5.0.6 on 2025-03-03 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(choices=[('ALA', 'Almaty'), ('NQZ', 'Astana'), ('SCO', 'Aktau'), ('AKX', 'Aktobe'), ('GUW', 'Atyrau'), ('AYK', 'Arkalyk'), ('BXH', 'Balkhash'), ('BXY', 'Baykonur'), ('DMB', 'Taraz'), ('DZN', 'Zhezkazgan'), ('KGF', 'Karaganda'), ('KOV', 'Kokshetau'), ('KSN', 'Kostanay'), ('KZO', 'Kyzylorda'), ('PWQ', 'Pavlodar'), ('PPK', 'Petropavlovsk'), ('TSE', 'Taldykorgan'), ('UKK', 'Oskemen'), ('URA', 'Uralsk'), ('PLX', 'Semey'), ('CIT', 'Shymkent'), ('CAY', 'Zaysan')], help_text='City where the organization is based', max_length=3, verbose_name='City'),
        ),
    ]
