# Generated by Django 5.0.6 on 2025-03-11 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_organization_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='abstract_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for abstracts', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Abstract project originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='article_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for articles', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Article originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='book_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for books', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Book project originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='course_work_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for course works', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Article originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='diploma_project_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for diploma projects', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Diploma project originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='diploma_thesis_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for diploma theses', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Diploma thesis originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='doctoral_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for doctoral works', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Doctoral originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='masters_thesis_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for masters thesis', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Masters thesis project originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='monograph_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for monographs', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Monograph project originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='other_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for other documents', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Other documents project originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='research_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for researches', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Research project originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='study_guide_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for study guides', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Study guide project originality threshold'),
        ),
        migrations.AddField(
            model_name='organization',
            name='textbook_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for textbooks', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Textbook project originality threshold'),
        ),
    ]
