# Generated by Django 5.0.6 on 2025-03-03 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_alter_organization_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='city',
            field=models.CharField(choices=[('ALA', 'Алматы'), ('NQZ', 'Астана'), ('SCO', 'Актау'), ('AKX', 'Актобе'), ('GUW', 'Атырау'), ('AYK', 'Аркалык'), ('BXH', 'Балхаш'), ('BXY', 'Байконур'), ('DMB', 'Тараз'), ('DZN', 'Жезказган'), ('KGF', 'Караганда'), ('KOV', 'Кокшетау'), ('KSN', 'Костанай'), ('KZO', 'Кызылорда'), ('PWQ', 'Павлодар'), ('PPK', 'Петропавловск'), ('TSE', 'Талдыкорган'), ('TTT', 'Темиртау'), ('UKK', 'Усть-Каменогорск'), ('URA', 'Уральск'), ('PLX', 'Семей'), ('CIT', 'Шымкент'), ('CAY', 'Зайсан')], help_text='City where the organization is based', max_length=3, verbose_name='City'),
        ),
    ]
