# Generated by Django 5.0.6 on 2025-03-11 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0010_organization_abstract_threshold_and_more'),
        ('organizations', '0011_alter_organization_city'),
    ]

    operations = [
    ]
