# Generated by Django 5.0.6 on 2025-03-11 21:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0012_merge_20250311_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='course_work_threshold',
            field=models.IntegerField(default=80, help_text='Minimum originality percentage required for course works', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Course work originality threshold'),
        ),
    ]
