# Generated by Django 5.0.6 on 2024-10-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
