# Generated by Django 5.0.6 on 2024-09-03 08:55

import django.core.validators
import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to=documents.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UP', 'Загружен'), ('PR', 'Проверяется'), ('CH', 'Проверен'), ('FA', 'Ошибка проверки')], default='PR', max_length=2)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uniqueness', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('human_written_percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('chatgpt_generated_percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('formulas_result', models.JSONField(blank=True, default=dict)),
                ('invisible_symbols_result', models.JSONField(blank=True, default=dict)),
                ('white_spaces_result', models.JSONField(blank=True, default=dict)),
                ('latin_letters_result', models.JSONField(blank=True, default=dict)),
                ('html_report', models.FileField(blank=True, null=True, upload_to=documents.models.user_directory_path)),
                ('originality_percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('plagiarism_percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)])),
                ('citation_percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)])),
                ('selfcitation_percentage', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)])),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='PlagiarismInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(blank=True)),
                ('indices', models.JSONField(blank=True, default=dict)),
                ('type', models.CharField(choices=[('PLAGIARISM', 'Плагиат'), ('QUOTE', 'Цитата'), ('SELFQUOTE', 'Самоцитирование')], default='PLAGIARISM', max_length=16)),
                ('title', models.CharField(blank=True, help_text='The title of the document from which the text was borrowed.', max_length=200)),
                ('module', models.CharField(blank=True, help_text='The module containing original document.', max_length=200)),
                ('shingles', models.JSONField(blank=True, default=dict, help_text='Intersecting shingles.')),
                ('fragments', models.JSONField(blank=True, default=dict, help_text='Borrowed text in preprocessed format.')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.report')),
            ],
        ),
    ]
