# Generated by Django 5.0.6 on 2024-09-03 14:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_report_shingles_total_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarisminstance',
            name='plagiarism_percentage',
            field=models.IntegerField(default=0, help_text='Counted by formula: plagiarised_shingles / total_shingles * 100', validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
