# Generated by Django 5.0.6 on 2024-09-03 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_plagiarisminstance_plagiarism_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='plagiarism_percentage',
            field=models.FloatField(default=0, help_text='Counted by formula: plagiarised_shingles / total_shingles * 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='chatgpt_generated_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='citation_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='human_written_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='originality_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='plagiarism_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='selfcitation_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)]),
        ),
    ]
