# Generated by Django 5.0.6 on 2024-09-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_plagiarisminstance_plagiarism_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='comments',
            field=models.TextField(blank=True, help_text='Comments to the report'),
        ),
    ]
