# Generated by Django 5.0.6 on 2024-09-07 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_report_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='comments',
        ),
    ]
