# Generated by Django 5.0.6 on 2024-09-09 16:40

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_remove_report_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(upload_to=documents.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt'])], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('UP', 'Uploaded'), ('PR', 'Checking'), ('CH', 'Checked'), ('FA', 'Error')], default='PR', max_length=2, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='fragments',
            field=models.JSONField(blank=True, default=dict, help_text='Borrowed text in preprocessed format.', verbose_name='fragments'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='indices',
            field=models.JSONField(blank=True, default=dict, verbose_name='indices'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='module',
            field=models.CharField(blank=True, help_text='The module containing original document.', max_length=200, verbose_name='module'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='plagiarism_percentage',
            field=models.FloatField(default=0, help_text='Counted by formula: plagiarised_shingles / total_shingles * 100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='plagiarism percentage'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='shingles',
            field=models.JSONField(blank=True, default=dict, help_text='Intersecting shingles.', verbose_name='shingles'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the document from which the text was borrowed.', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='type',
            field=models.CharField(choices=[('PLAGIARISM', 'Плагиат'), ('QUOTE', 'Цитата'), ('SELFQUOTE', 'Самоцитирование')], default='PLAGIARISM', max_length=16, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='url',
            field=models.TextField(blank=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='report',
            name='chatgpt_generated_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='chatgpt generated percentage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='citation_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='citation percentage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='report',
            name='formulas_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='formulas result'),
        ),
        migrations.AlterField(
            model_name='report',
            name='html_report',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.user_directory_path, verbose_name='html report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='human_written_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='human written percentage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='invisible_symbols_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='invisible symbols result'),
        ),
        migrations.AlterField(
            model_name='report',
            name='latin_letters_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='latin letters result'),
        ),
        migrations.AlterField(
            model_name='report',
            name='originality_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='originality percentage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='plagiarism_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='plagiarism percentage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='selfcitation_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(0)], verbose_name='selfcitation percentage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='shingles_total_number',
            field=models.IntegerField(default=0, help_text='Total number of shingles in the document', verbose_name='shingles total number'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='uniqueness',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='uniqueness'),
        ),
        migrations.AlterField(
            model_name='report',
            name='white_spaces_result',
            field=models.JSONField(blank=True, default=dict, verbose_name='white spaces result'),
        ),
    ]
