# Generated by Django 5.0.6 on 2024-09-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_document_created_at_alter_document_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='type',
            field=models.CharField(choices=[('PLAGIARISM', 'Plagiarism'), ('QUOTE', 'Citation'), ('SELFQUOTE', 'Selfcitation')], default='PLAGIARISM', max_length=16, verbose_name='type'),
        ),
    ]
