# Generated by Django 5.0.6 on 2024-09-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_plagiarisminstance_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.CharField(default='', max_length=200, verbose_name='author'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('DOCTORAL', 'Doctoral dissertation'), ('MASTERS', 'Masters dissertation'), ('STUDYGUIDE', 'Study guide'), ('TEXTBOOK', 'Textbook'), ('BOOK', 'Book'), ('RESEARCH', 'Research'), ('MONOGRAPH', 'Monograph'), ('ABSTRACT', 'Abstract')], default='ARTICLE', max_length=16, verbose_name='document type'),
        ),
    ]
