# Generated by Django 5.0.6 on 2024-09-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_document_author_document_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='plagiarisminstance',
            name='plagiarism_characters_count',
            field=models.IntegerField(default=0, help_text='Characters count of plagiarism instance.', verbose_name='plagiarism characters count'),
        ),
        migrations.AddField(
            model_name='plagiarisminstance',
            name='plagiarism_ranges',
            field=models.JSONField(blank=True, default=dict, help_text='range of borrowed characters: start, end, length.', verbose_name='plagiarism ranges'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='url',
            field=models.TextField(blank=True, help_text='Link to the document from which the text was borrowed.', verbose_name='url'),
        ),
    ]
