# Generated by Django 5.0.6 on 2024-09-15 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_plagiarisminstance_plagiarism_characters_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='citation_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='citation percentage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='plagiarism_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='plagiarism percentage'),
        ),
        migrations.AlterField(
            model_name='report',
            name='selfcitation_percentage',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='selfcitation percentage'),
        ),
    ]
