# Generated by Django 5.0.6 on 2024-09-17 13:09

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0011_alter_report_citation_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_certificate',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.user_directory_path, verbose_name='certificate'),
        ),
    ]
