# Generated by Django 5.0.6 on 2024-09-17 15:08

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_report_pdf_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='html_report',
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to=documents.models.user_directory_path, verbose_name='pdf report'),
        ),
    ]
