# Generated by Django 5.0.6 on 2024-10-07 08:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_report_internet_originality_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='internet_originality_percentage',
            field=models.FloatField(default=0, help_text='Text originality percentage from Internet module', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='originality percentage (internet)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='internet_plagiarism_percentage',
            field=models.FloatField(default=0, help_text='Text plagiarism percentage from Internet module', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='plagiarism percentage (internet)'),
        ),
    ]
