# Generated by Django 5.0.6 on 2024-10-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_alter_report_internet_originality_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tasks_completed',
            field=models.IntegerField(default=0, help_text='How many tasks is completed'),
        ),
    ]
