# Generated by Django 5.0.6 on 2024-10-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_document_tasks_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='text_content',
            field=models.TextField(blank=True, help_text='Stores the extracted text of the document', null=True, verbose_name='text content'),
        ),
    ]
