# Generated by Django 5.0.6 on 2024-10-27 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_document_text_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='include_ocr',
            field=models.BooleanField(default=False, help_text='Extract text using OCR recognition'),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_languages',
            field=models.CharField(default='rus', help_text="OCR languages e.g., 'eng+rus+kaz'", max_length=30),
        ),
    ]
