# Generated by Django 5.0.6 on 2024-10-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_document_include_ocr_document_ocr_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='ocr_languages',
            field=models.CharField(default='rus', help_text="For example: 'eng+rus+kaz'", max_length=30, verbose_name='OCR languages'),
        ),
    ]
