# Generated by Django 5.0.6 on 2024-10-27 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_alter_document_ocr_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('DOCTORAL', 'Doctoral dissertation'), ('MASTERS', 'Masters dissertation'), ('STUDYGUIDE', 'Study guide'), ('TEXTBOOK', 'Textbook'), ('BOOK', 'Book'), ('RESEARCH', 'Research'), ('MONOGRAPH', 'Monograph'), ('ABSTRACT', 'Abstract')], default='ARTICLE', max_length=16, verbose_name='Document type'),
        ),
        migrations.AlterField(
            model_name='document',
            name='include_ocr',
            field=models.BooleanField(default=False, help_text='Extract text using OCR recognition (only pdf files)', verbose_name='Enable OCR'),
        ),
    ]
