# Generated by Django 5.0.6 on 2024-11-04 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_alter_report_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='documents.document'),
        ),
    ]
