# Generated by Django 5.0.6 on 2024-11-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_alter_report_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='estimated_completion',
            field=models.DateTimeField(blank=True, help_text='The estimated time when the document will be fully processed', null=True, verbose_name='estimated check completion'),
        ),
    ]
