# Generated by Django 5.0.6 on 2024-11-21 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0024_document_estimated_completion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('COURSE WORK', 'Course work'), ('DOCTORAL', 'Doctoral dissertation'), ('DIPLOMA THESIS', 'Diploma thesis'), ('DIPLOMA PROJECT', 'Diploma project'), ('MASTERS', 'Masters dissertation'), ('STUDYGUIDE', 'Study guide'), ('TEXTBOOK', 'Textbook'), ('BOOK', 'Book'), ('RESEARCH', 'Research'), ('MONOGRAPH', 'Monograph'), ('ABSTRACT', 'Abstract')], default='ARTICLE', max_length=16, verbose_name='Document type'),
        ),
    ]
