# Generated by Django 5.0.6 on 2024-11-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_alter_document_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='author',
            field=models.CharField(default='', max_length=512, verbose_name='author'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=512, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=512, verbose_name='Folder Name'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the document from which the text was borrowed.', max_length=512, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=512, verbose_name='title'),
        ),
    ]
