# Generated by Django 5.0.6 on 2024-12-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_alter_document_author_alter_document_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=2048, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the document from which the text was borrowed.', max_length=2048, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=2048, verbose_name='title'),
        ),
    ]
