# Generated by Django 5.0.6 on 2024-12-03 16:47

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0028_alter_document_title_alter_plagiarisminstance_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(max_length=2048, upload_to=documents.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt'])], verbose_name='description'),
        ),
    ]
