# Generated by Django 5.0.6 on 2024-12-04 06:25

import django.core.validators
import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0029_alter_document_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(max_length=1024, upload_to=documents.models.user_directory_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'txt'])], verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='plagiarisminstance',
            name='title',
            field=models.CharField(blank=True, help_text='The title of the document from which the text was borrowed.', max_length=1024, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='title'),
        ),
    ]
