# Generated by Django 5.0.6 on 2025-03-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0030_alter_document_document_alter_document_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='department',
            field=models.CharField(blank=True, help_text='Department name of the student whose Document is under check', max_length=256, null=True, verbose_name='Department'),
        ),
    ]
