# Generated by Django 5.0.6 on 2025-03-11 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0031_document_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='department',
            field=models.CharField(blank=True, help_text='Department name', max_length=256, null=True, verbose_name='Department'),
        ),
    ]
