# Generated by Django 5.0.6 on 2024-09-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_created_at_news_slug_news_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Is the news approved'),
        ),
    ]
